all:
  children:
    production:
      hosts:
        n8n-production:
          ansible_host: 142.132.239.135
          ansible_port: 25222
          ansible_user: deploy
          deploy_user: deploy
          sudo_user: kulibin
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          # Server-specific variables
          server_domain: openorbit.pro
          letsencrypt_email: leemour@gmail.com

    staging:
      hosts:
        n8n-staging:
          ansible_host: 142.132.239.135
          ansible_port: 25222
          ansible_user: deploy
          deploy_user: deploy
          sudo_user: kulibin
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          server_domain: staging.openorbit.pro
          letsencrypt_email: leemour@gmail.com

  vars:
    # Global variables for all servers
    docker_network_name: n8n-network
