---
- name: Deploy N8N and Global Proxy
  hosts: all
  become: yes
  vars_files:
    - ../vars/secrets.yml

  tasks:
    - name: Include server setup tasks
      include_tasks: ../tasks/server-setup.yml

    - name: Include global proxy setup
      include_tasks: ../tasks/proxy-setup.yml

    - name: Include N8N deployment
      include_tasks: ../tasks/n8n-deploy.yml

    - name: Include backup setup
      include_tasks: ../tasks/backup-setup.yml
      when: enable_automated_backups | default(false)

    - name: Include monitoring setup
      include_tasks: ../tasks/monitoring.yml
      when: enable_monitoring | default(false)
