---
# Rollback to previous release
- name: Get current release
  stat:
    path: "{{ apps_dir }}/current"
  register: current_release

- name: Get previous release
  shell: |
    cd {{ apps_dir }}/releases
    ls -t | head -n 2 | tail -n 1
  register: previous_release
  become_user: "{{ ansible_user }}"

- name: Stop current services
  docker_compose:
    project_src: "{{ apps_dir }}/current"
    state: absent
  become_user: "{{ ansible_user }}"
  ignore_errors: yes

- name: Switch to previous release
  file:
    src: "{{ apps_dir }}/releases/{{ previous_release.stdout }}"
    dest: "{{ apps_dir }}/current"
    state: link
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Start previous release
  docker_compose:
    project_src: "{{ apps_dir }}/current"
    state: present
  become_user: "{{ ansible_user }}"

- name: Show rollback info
  debug:
    msg: "Rolled back to release: {{ previous_release.stdout }}"
